idf_component_register(SRCS "main.c"
                            "ai_mgr.c"
                            "auth_mgr.c"
                            "mqtt_mgr.c"
                            "app_config.c"
                            "camera_mgr.c"
                            "console_cmds.c"
                            "event_mgr.c"
                            "llm_mgr.c"
                            "motion_mgr.c"
                            "person_mgr.cc"
                            "models/person_detect_model_data.cc"
                            "status_led.c"
                            "stats_mgr.c"
                            "sysmon.c"
                            "web_server.c"
                            "wifi_mgr.c"
                       INCLUDE_DIRS "."
                       EMBED_TXTFILES "web/index.html")
